GET https://api.github.com/repos/facebook/react/labels

###

GET https://api.github.com/user
Content-Type: application/json
Authorization: : Bearer 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